### ISSUE TITLE
Upgrade bblfsh sdk to v2

### ISSUE THREAD

**Issue by eiso** [bblfsh/web#143]
So that we can show people the new UAST's

**Comment by smacker** [comment]
There is no sdk v2 release.
Also as I understand sematic UAST should work with the current client/sdk (didn't check though).

**Comment by dennwc** [comment]
Dashboard will require an update once v2 protocol is released.

I will post all the details here once it's ready.

**Comment by dennwc** [comment]
We are super close to releasing the v2 support in Go client and drivers, so we can start thinking of ways to integrate it.

I would like to highlight some differences in the v2 here and split them into separate issues later.

* The representation is similar to JSON. Meaning there are two kinds of branch nodes: `Object` (unordered map) and `Array` (ordered, but no attributes or roles), and few kinds of `Values` (leaf nodes): `nil`, `string`, `int`, `uint`, `float`, `bool`.
* There is no special fields in the proto message (no strict schema). Meaning that `InternalType` is now just a regular key called `@type` in the `Object` map.
* There is no `Children` array in nodes. Instead, an `Object` can have a named field pointing to an `Array`.
* There could be more than 2 positional fields. We still provide `start`/`end` positions, but some drivers might emit more. Would be nice to display it as well.

Also, we expect few changes in XPath, but most important is that Dashboard should be able to display XPath results that return a primitive values (strings, ints) instead of nodes.

We will release a Go client as the first step, that will directly decode v2 UAST without libuast, and will not support XPath. During this time Apps will be able to test new UASTs by using this client. Later we will update libuast and will switch the client to it. After this point XPath will be supported as well.

**Comment by smacker** [comment]
We have many different options how to do that:

1. Convert new uast to old dashboard-internal-uast-json and hack-in primitive values (changes only on the server)
2. Convert new uast to some new-internal-uast-json (most probably just serialize structs to json) and change frontend accordingly
3. Send protobuf to the browser, reuse some parts of this branch https://github.com/smacker/dashboard/tree/bblfsh_js to display it (similar changes to point 2 but instead of converting to json, read protobuf directly)
4. Wait for new libuast, update js client, reuse work from https://github.com/smacker/dashboard/tree/bblfsh_js (with changes similar to point 3) (don't use client-go at all)

Most probably p2 is the fasted and simplest (though still isn't free).
p4 is the most hard-core but improves user experience (instant filtering)

**Comment by eiso** [comment]
@smacker just my two cents, while the geek in me loves p4, it probably shouldn't be where we are spending our time.

**Comment by smacker** [comment]
Agree. Another note: I don't see anything related to new UAST for apps in our OKRs.

And even the fastest changes aren't that fast to just slip it in (taking into account uast-viewer isn't really schema agnostic https://github.com/bblfsh/uast-viewer/issues/43 yet)

**Comment by eiso** [comment]
@smacker you're right since we didn't move over the UAST v2 OKR from Q2 since we thought it would only be a few weeks into Q3. This quarter is already busy enough, so I won't make any changes to our priorities that relate to the applications team for this.

**Comment by bzz** [comment]
@smacker thank you for thoughtful analysis and suggestions!

For me, this is part of the Dashboard maintenance, and we all agreed that such things are just part of our life and work, on top of the OKRs.

Besides, we already discussed and have agreed up on migration to UASTv2 on gemini and lookout.

But as displaying UASTv2 properly would require changes here and in uast-veiwer (and thus most probably,  in gitbase-playgound) - let me double-check the priorities with @mcuadros and get back to you guys here.

**Comment by smola** [comment]
Yes, maintenance of current projects is always part of our job. We should probably favor proposal 2, we just want to make dashboard compatible with sdk v2, improving functionality is completely secondary at this point.

**Comment by smacker** [comment]
@bzz we might want to add this issues in our backlog then:

- https://github.com/bblfsh/uast-viewer/issues/43
- https://github.com/bblfsh/uast-viewer/issues/44
- https://github.com/bblfsh/uast-viewer/issues/50

we will need to fix them for the upgrade.

Most probably none of them require much code or time. Just need to make sure the viewer is flexible enough for changes of the format in the future. (new "special" fields, annotated/semantic mode and so on)

In theory after resolving them to support new uast on frontend we will just to need create a correct configuration (define special fields like `@pos` that should be hidden if the toggler is off, how to get information for position index and few other things)

**Comment by bzz** [comment]
👍 after discussion with @mcuadros and @smola - adding those to the backlog.

**Comment by bzz** [comment]
@smacker can see the issues above are closed, could you please post here what if there is anything left to be done here? Thanks!

**Comment by smacker** [comment]
progress: uast-viewer doesn’t depend on uast v1 anymore. I’m trying to figure out how to work with uast-v2 now on backend.
in theory correct json created from uast-v2 + configuration for uast-viewer and it should work.
but it’s theory :smile:

**Comment by smacker** [comment]
Update:

More frontend (I missed the feature of a node inside properties in uast2 originally 🤦‍♂️ ):
https://github.com/bblfsh/uast-viewer/pull/56

WIP PR in dashboard:
https://github.com/bblfsh/web/pull/152

There is no libuast for uast2 yet, so x-path filtering just doesn't work.
To allow results with primitive types we will need to wrap it in a fake array node and most probably it will work (though I didn't test it, maybe some other changes on FE will be needed)

**Comment by smacker** [comment]
just a screenshot of how new UAST2 is going to look in dashboard:

<img width="1465" alt="screen shot 2018-08-24 at 18 43 33" src="https://user-images.githubusercontent.com/406916/44596783-cd578780-a7cd-11e8-82bd-840732cf4e87.png">

**Comment by dennwc** [comment]
XPath now works for UASTv2 in the Go client ;)

**Comment by smacker** [comment]
Fixed in master. The only problem left: https://github.com/bblfsh/web/issues/162
